version: '3.8'
services:
  php-apache-enironment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: creature_wars_com
      MYSQL_USER: creature_wars_com
      MYSQL_PASSWORD: root
      TB_PREFIX: s1_
    ports:
      - 9906:3306
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8081:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on: 
      - db